name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup environemnt
        env:
          ENV_FILE: ${{ secrets.ALL_ENV }}
        run: |
          echo $ENV_FILE | base64 --decode > .env

      - name: Download dataset
        run: python -m src.scripts.clone

      - name: Build web UI
        run: |
          cd src/web
          npm install
          npm run build

      - name: Build static site
        run: python -m src.static-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
